# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/data/Dropbox/Trabalho/QGIS/Plugins-QGIS/WalkingTime/ui_walkingtime.ui'
#
# Created: Sat Dec 28 14:52:16 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WalkingTime(object):
    def setupUi(self, WalkingTime):
        WalkingTime.setObjectName(_fromUtf8("WalkingTime"))
        WalkingTime.resize(340, 474)
        self.layoutWidget = QtGui.QWidget(WalkingTime)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 12, 321, 452))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_inputs = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_inputs.setObjectName(_fromUtf8("groupBox_inputs"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_inputs)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox_inputs)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.comboBox_elevation_layer = QtGui.QComboBox(self.groupBox_inputs)
        self.comboBox_elevation_layer.setObjectName(_fromUtf8("comboBox_elevation_layer"))
        self.gridLayout.addWidget(self.comboBox_elevation_layer, 2, 1, 1, 1)
        self.comboBox_line_layer = QtGui.QComboBox(self.groupBox_inputs)
        self.comboBox_line_layer.setObjectName(_fromUtf8("comboBox_line_layer"))
        self.gridLayout.addWidget(self.comboBox_line_layer, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_inputs)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.checkBox_selected_features_only = QtGui.QCheckBox(self.groupBox_inputs)
        self.checkBox_selected_features_only.setObjectName(_fromUtf8("checkBox_selected_features_only"))
        self.gridLayout.addWidget(self.checkBox_selected_features_only, 0, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_inputs, 0, 0, 1, 2)
        self.groupBox_3_parameters = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3_parameters.setObjectName(_fromUtf8("groupBox_3_parameters"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3_parameters)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3_parameters)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBox_base_velocity = QtGui.QDoubleSpinBox(self.groupBox_3_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_base_velocity.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_base_velocity.setSizePolicy(sizePolicy)
        self.doubleSpinBox_base_velocity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_base_velocity.setObjectName(_fromUtf8("doubleSpinBox_base_velocity"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_base_velocity, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3_parameters, 1, 0, 1, 2)
        self.groupBox_2_outputs = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2_outputs.setObjectName(_fromUtf8("groupBox_2_outputs"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2_outputs)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_update_fields = QtGui.QRadioButton(self.groupBox_2_outputs)
        self.radioButton_update_fields.setChecked(True)
        self.radioButton_update_fields.setObjectName(_fromUtf8("radioButton_update_fields"))
        self.gridLayout_2.addWidget(self.radioButton_update_fields, 0, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_2_outputs)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2_outputs)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.radioButton_new_fields = QtGui.QRadioButton(self.groupBox_2_outputs)
        self.radioButton_new_fields.setEnabled(False)
        self.radioButton_new_fields.setObjectName(_fromUtf8("radioButton_new_fields"))
        self.gridLayout_2.addWidget(self.radioButton_new_fields, 3, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.groupBox_2_outputs)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2_outputs)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.comboBox_time_field = QtGui.QComboBox(self.groupBox_2_outputs)
        self.comboBox_time_field.setObjectName(_fromUtf8("comboBox_time_field"))
        self.gridLayout_2.addWidget(self.comboBox_time_field, 1, 1, 1, 1)
        self.comboBox_rev_time_field = QtGui.QComboBox(self.groupBox_2_outputs)
        self.comboBox_rev_time_field.setObjectName(_fromUtf8("comboBox_rev_time_field"))
        self.gridLayout_2.addWidget(self.comboBox_rev_time_field, 2, 1, 1, 1)
        self.lineEdit_rev_time_field_name = QtGui.QLineEdit(self.groupBox_2_outputs)
        self.lineEdit_rev_time_field_name.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev_time_field_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev_time_field_name.setSizePolicy(sizePolicy)
        self.lineEdit_rev_time_field_name.setObjectName(_fromUtf8("lineEdit_rev_time_field_name"))
        self.gridLayout_2.addWidget(self.lineEdit_rev_time_field_name, 5, 1, 1, 1)
        self.lineEdit_time_field_name = QtGui.QLineEdit(self.groupBox_2_outputs)
        self.lineEdit_time_field_name.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_time_field_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_time_field_name.setSizePolicy(sizePolicy)
        self.lineEdit_time_field_name.setObjectName(_fromUtf8("lineEdit_time_field_name"))
        self.gridLayout_2.addWidget(self.lineEdit_time_field_name, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2_outputs, 2, 0, 1, 2)
        self.pushButton_help = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_help.setObjectName(_fromUtf8("pushButton_help"))
        self.gridLayout_4.addWidget(self.pushButton_help, 3, 0, 1, 1)
        self.buttonBox_ok_cancel = QtGui.QDialogButtonBox(self.layoutWidget)
        self.buttonBox_ok_cancel.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_ok_cancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_ok_cancel.setObjectName(_fromUtf8("buttonBox_ok_cancel"))
        self.gridLayout_4.addWidget(self.buttonBox_ok_cancel, 3, 1, 1, 1)

        self.retranslateUi(WalkingTime)
        QtCore.QObject.connect(self.buttonBox_ok_cancel, QtCore.SIGNAL(_fromUtf8("accepted()")), WalkingTime.accept)
        QtCore.QObject.connect(self.buttonBox_ok_cancel, QtCore.SIGNAL(_fromUtf8("rejected()")), WalkingTime.reject)
        QtCore.QMetaObject.connectSlotsByName(WalkingTime)

    def retranslateUi(self, WalkingTime):
        WalkingTime.setWindowTitle(QtGui.QApplication.translate("WalkingTime", "WalkingTime", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_inputs.setTitle(QtGui.QApplication.translate("WalkingTime", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("WalkingTime", "Line Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("WalkingTime", "Elevation raster layer", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_selected_features_only.setText(QtGui.QApplication.translate("WalkingTime", "Use only selected features", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3_parameters.setTitle(QtGui.QApplication.translate("WalkingTime", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("WalkingTime", "Plain velocity (km\\ h)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2_outputs.setTitle(QtGui.QApplication.translate("WalkingTime", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_update_fields.setText(QtGui.QApplication.translate("WalkingTime", "Update fields", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("WalkingTime", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("WalkingTime", "Reverse time", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_new_fields.setText(QtGui.QApplication.translate("WalkingTime", "Create new fields", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("WalkingTime", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("WalkingTime", "Reverse time", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_help.setText(QtGui.QApplication.translate("WalkingTime", "Help", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WalkingTime = QtGui.QDialog()
    ui = Ui_WalkingTime()
    ui.setupUi(WalkingTime)
    WalkingTime.show()
    sys.exit(app.exec_())

