# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\alexandre.neto\Dropbox\Trabalho\Plugins QGIS\WalkingTime\ui_walkingtime.ui'
#
# Created: Thu Jan 02 17:05:50 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WalkingTime(object):
    def setupUi(self, WalkingTime):
        WalkingTime.setObjectName(_fromUtf8("WalkingTime"))
        WalkingTime.resize(320, 396)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WalkingTime.sizePolicy().hasHeightForWidth())
        WalkingTime.setSizePolicy(sizePolicy)
        WalkingTime.setSizeGripEnabled(False)
        self.gridLayout_5 = QtGui.QGridLayout(WalkingTime)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_inputs = QtGui.QGroupBox(WalkingTime)
        self.groupBox_inputs.setObjectName(_fromUtf8("groupBox_inputs"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_inputs)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_elevation_layer = QtGui.QComboBox(self.groupBox_inputs)
        self.comboBox_elevation_layer.setObjectName(_fromUtf8("comboBox_elevation_layer"))
        self.gridLayout.addWidget(self.comboBox_elevation_layer, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_inputs)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_inputs)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.checkBox_selected_features_only = QtGui.QCheckBox(self.groupBox_inputs)
        self.checkBox_selected_features_only.setObjectName(_fromUtf8("checkBox_selected_features_only"))
        self.gridLayout.addWidget(self.checkBox_selected_features_only, 0, 0, 1, 2)
        self.comboBox_line_layer = QtGui.QComboBox(self.groupBox_inputs)
        self.comboBox_line_layer.setObjectName(_fromUtf8("comboBox_line_layer"))
        self.gridLayout.addWidget(self.comboBox_line_layer, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_inputs, 0, 0, 1, 2)
        self.groupBox_3_parameters = QtGui.QGroupBox(WalkingTime)
        self.groupBox_3_parameters.setObjectName(_fromUtf8("groupBox_3_parameters"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3_parameters)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3_parameters)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBox_base_velocity = QtGui.QDoubleSpinBox(self.groupBox_3_parameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_base_velocity.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_base_velocity.setSizePolicy(sizePolicy)
        self.doubleSpinBox_base_velocity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_base_velocity.setSingleStep(0.1)
        self.doubleSpinBox_base_velocity.setProperty("value", 5.0)
        self.doubleSpinBox_base_velocity.setObjectName(_fromUtf8("doubleSpinBox_base_velocity"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_base_velocity, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3_parameters, 1, 0, 1, 2)
        self.groupBox_2_outputs = QtGui.QGroupBox(WalkingTime)
        self.groupBox_2_outputs.setObjectName(_fromUtf8("groupBox_2_outputs"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2_outputs)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButton_update_fields = QtGui.QRadioButton(self.groupBox_2_outputs)
        self.radioButton_update_fields.setChecked(True)
        self.radioButton_update_fields.setObjectName(_fromUtf8("radioButton_update_fields"))
        self.gridLayout_2.addWidget(self.radioButton_update_fields, 0, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_2_outputs)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2_outputs)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.radioButton_new_fields = QtGui.QRadioButton(self.groupBox_2_outputs)
        self.radioButton_new_fields.setEnabled(True)
        self.radioButton_new_fields.setObjectName(_fromUtf8("radioButton_new_fields"))
        self.gridLayout_2.addWidget(self.radioButton_new_fields, 3, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.groupBox_2_outputs)
        self.label_6.setEnabled(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2_outputs)
        self.label_7.setEnabled(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.comboBox_time_field = QtGui.QComboBox(self.groupBox_2_outputs)
        self.comboBox_time_field.setObjectName(_fromUtf8("comboBox_time_field"))
        self.gridLayout_2.addWidget(self.comboBox_time_field, 1, 1, 1, 1)
        self.comboBox_rev_time_field = QtGui.QComboBox(self.groupBox_2_outputs)
        self.comboBox_rev_time_field.setObjectName(_fromUtf8("comboBox_rev_time_field"))
        self.gridLayout_2.addWidget(self.comboBox_rev_time_field, 2, 1, 1, 1)
        self.lineEdit_rev_time_field_name = QtGui.QLineEdit(self.groupBox_2_outputs)
        self.lineEdit_rev_time_field_name.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_rev_time_field_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_rev_time_field_name.setSizePolicy(sizePolicy)
        self.lineEdit_rev_time_field_name.setObjectName(_fromUtf8("lineEdit_rev_time_field_name"))
        self.gridLayout_2.addWidget(self.lineEdit_rev_time_field_name, 5, 1, 1, 1)
        self.lineEdit_time_field_name = QtGui.QLineEdit(self.groupBox_2_outputs)
        self.lineEdit_time_field_name.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_time_field_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_time_field_name.setSizePolicy(sizePolicy)
        self.lineEdit_time_field_name.setObjectName(_fromUtf8("lineEdit_time_field_name"))
        self.gridLayout_2.addWidget(self.lineEdit_time_field_name, 4, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2_outputs, 2, 0, 1, 2)
        self.pushButton_help = QtGui.QPushButton(WalkingTime)
        self.pushButton_help.setObjectName(_fromUtf8("pushButton_help"))
        self.gridLayout_4.addWidget(self.pushButton_help, 3, 0, 1, 1)
        self.buttonBox_ok_cancel = QtGui.QDialogButtonBox(WalkingTime)
        self.buttonBox_ok_cancel.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_ok_cancel.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_ok_cancel.setObjectName(_fromUtf8("buttonBox_ok_cancel"))
        self.gridLayout_4.addWidget(self.buttonBox_ok_cancel, 3, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)

        self.retranslateUi(WalkingTime)
        QtCore.QObject.connect(self.buttonBox_ok_cancel, QtCore.SIGNAL(_fromUtf8("accepted()")), WalkingTime.accept)
        QtCore.QObject.connect(self.buttonBox_ok_cancel, QtCore.SIGNAL(_fromUtf8("rejected()")), WalkingTime.reject)
        QtCore.QObject.connect(self.radioButton_update_fields, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_3.setEnabled)
        QtCore.QObject.connect(self.radioButton_update_fields, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBox_time_field.setEnabled)
        QtCore.QObject.connect(self.radioButton_update_fields, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_4.setEnabled)
        QtCore.QObject.connect(self.radioButton_update_fields, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBox_rev_time_field.setEnabled)
        QtCore.QObject.connect(self.radioButton_new_fields, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_6.setEnabled)
        QtCore.QObject.connect(self.radioButton_new_fields, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_time_field_name.setEnabled)
        QtCore.QObject.connect(self.radioButton_new_fields, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_7.setEnabled)
        QtCore.QObject.connect(self.radioButton_new_fields, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lineEdit_rev_time_field_name.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(WalkingTime)

    def retranslateUi(self, WalkingTime):
        WalkingTime.setWindowTitle(_translate("WalkingTime", "WalkingTime", None))
        self.groupBox_inputs.setTitle(_translate("WalkingTime", "Inputs", None))
        self.label.setText(_translate("WalkingTime", "Line Layer", None))
        self.label_2.setText(_translate("WalkingTime", "Elevation raster layer", None))
        self.checkBox_selected_features_only.setText(_translate("WalkingTime", "Use only selected features", None))
        self.groupBox_3_parameters.setTitle(_translate("WalkingTime", "Parameters", None))
        self.label_5.setText(_translate("WalkingTime", "Flat terrain velocity (km\\ h)", None))
        self.groupBox_2_outputs.setTitle(_translate("WalkingTime", "Output", None))
        self.radioButton_update_fields.setText(_translate("WalkingTime", "Update fields", None))
        self.label_3.setText(_translate("WalkingTime", "Time", None))
        self.label_4.setText(_translate("WalkingTime", "Reverse time", None))
        self.radioButton_new_fields.setText(_translate("WalkingTime", "Create new fields", None))
        self.label_6.setText(_translate("WalkingTime", "Time", None))
        self.label_7.setText(_translate("WalkingTime", "Reverse time", None))
        self.pushButton_help.setText(_translate("WalkingTime", "Help", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WalkingTime = QtGui.QDialog()
    ui = Ui_WalkingTime()
    ui.setupUi(WalkingTime)
    WalkingTime.show()
    sys.exit(app.exec_())

